name: Terraform pipeline

trigger:
  - develop

stages:
  - stage: TerraformPlan
    jobs:
      - job: Terraform_Plan
        displayName: Terraform Plan
        continueOnError: false
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              cd ..
              mkdir artifact-directory    
            displayName: Making Artifact Directory 

          - script: |
              files=$(git diff-tree --no-commit-id --name-only -r $(Build.SourceVersion))
              for file in $files
              do
                parsed_file=${file##*/}
                if [[ "$parsed_file" =~ .(tf|tfvars|hcl)$ ]]; then
                  parsed_path=${file%/*}
                  echo "Terragrunt configuration file changes found: ${parsed_path}"
                  echo "##vso[task.setvariable variable=tf_path]$parsed_path"
                  echo "##vso[task.setvariable variable=tf_config_validated]2"
                else
                  echo "##vso[task.setvariable variable=tf_path]$parsed_path"
                  echo "No Terragrunt configuration file changes found"
                  echo "##vso[task.setvariable variable=tf_config_validated]1"
                fi
              done
            displayName: Evaluating Commit for Terragrunt Configuration Changes

          - task: TerraformInstaller@0
            displayName: Use latest Terraform
            inputs:
              terraformVersion: latest
            condition: eq(variables['tf_config_validated'], '2')

          - script: wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.24.0/terragrunt_linux_amd64
            displayName: Retrieving Terragrunt
            condition: eq(variables['tf_config_validated'], '2')

          - script: |
              chmod +x terragrunt_linux_amd64
              sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
            displayName: Ensuring Terragrunt Permissions
            condition: eq(variables['tf_config_validated'], '2')

          - script: |
              terragrunt plan -out=terraform.plan -input=false
              tf_plan_path=$(find . -name terraform.plan -printf '%h\n')
              echo $tf_plan_path
              echo "terraform.plan file located: ${tf_plan_path}/terraform.plan"
              echo "##vso[task.setvariable variable=tf_plan_path;isOutput=true]$tf_plan_path"
              echo "##vso[task.setvariable variable=tf_plan_generated]2"
              # terragrunt apply -auto-approve
            workingDirectory: '$(Build.SourcesDirectory)/$(TF_PATH)'
            displayName: Initialize Terraform\Terragrunt
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              TERRAGRUNT_IAM_ROLE: $(TERRAGRUNT_IAM_ROLE)
              TERRAFORM_STATE_BUCKET: $(TERRAFORM_STATE_BUCKET)
            condition: eq(variables['tf_config_validated'], '2')

          - script: |
              base=$(basename $PWD)
              cd ..
              tar -czf $base.tar.gz $base
              mv -f $base.tar.gz artifact-directory/
            displayName: Compressing Terraform Configuration files
            condition: eq(variables['tf_plan_generated'], '2')

          - task: PublishPipelineArtifact@0
            inputs:
              artifactName: terraform-plan-artifact
              targetPath: '../artifact-directory'
            condition: eq(variables['tf_plan_generated'], '2')

  - stage: TerraformApply
    dependsOn: TerraformPlan
    jobs:
    - deployment: Terraform_Apply
      displayName: Applying Terraform Configuration
      pool:
        vmImage: ubuntu-latest
      environment: 'Terraform-Apply-Manual'
      strategy:
        runOnce:
          deploy:
            steps:
              - script: |
                  base=$(basename $PWD)
                  cd ../terraform-plan-artifact
                  tar -xvf $base.tar.gz
                  ls -lh
                displayName: Decomressing Terraform Plan Artifact

              - task: TerraformInstaller@0
                displayName: Use latest Terraform
                inputs:
                  terraformVersion: latest
    
              - script: wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.24.0/terragrunt_linux_amd64
                displayName: Retrieving Terragrunt
    
              - script: |
                  chmod +x terragrunt_linux_amd64
                  sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
                displayName: Ensuring Terragrunt Permissions

              - script: |
                  cd ../terraform-plan-artifact
                  echo "Finding Current Terragrunt build Directory"
                  terragrunt_cache_path=$(find . -name .terragrunt-cache -printf '%h\n')
                  echo $terragrunt_cache_path
                  echo "##vso[task.setvariable variable=terragrunt_cache_path]$terragrunt_cache_path"
                displayName: Locate Configuration Path via terragrunt.cache directory

              - script: |
                  echo 'Applying Terragrunt Plan File...'
                  terragrunt apply -auto-approve
                workingDirectory: '../terraform-plan-artifact/$(TERRAGRUNT_CACHE_PATH)'
                displayName: Apply Terraform Configurtion Changes
                env:
                  AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
                  AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
                  TERRAGRUNT_IAM_ROLE: $(TERRAGRUNT_IAM_ROLE)
                  TERRAFORM_STATE_BUCKET: $(TERRAFORM_STATE_BUCKET)